### ISSUE TITLE
Does RMG-Py allow adjlists with benzene bonds?

### ISSUE THREAD

**Issue by connie** [GreenGroup/RMG-Py#163]
I thought we allowed adjlists with benzene bonds in the input files, with RDKit doing the  kekulization.  

Using benzene in the input.py file: 
1 C 0 {2,B} {6,B}
2 C 0 {1,B} {3,B}
3 C 0 {2,B} {4,B}
4 C 0 {3,B} {5,B}
5 C 0 {4,B} {6,B}
6 C 0 {1,B} {5,B}

We get a transport database error:
```python
Traceback (most recent call last):
  File "../../../rmg.py", line 147, in <module>
    rmg.execute(args)
  File "/home/connie/Research/Code/RMG-Py/rmgpy/rmg/main.py", line 364, in execute
    self.initialize(args)
  File "/home/connie/Research/Code/RMG-Py/rmgpy/rmg/main.py", line 350, in initialize
    spec.generateTransportData(self.database)
  File "/home/connie/Research/Code/RMG-Py/rmgpy/rmg/model.py", line 245, in generateTransportData
    self.transportData = database.transport.getTransportProperties(self)[0]
  File "/home/connie/Research/Code/RMG-Py/rmgpy/data/transport.py", line 278, in getTransportProperties
    transport = self.getTransportPropertiesViaGroupEstimates(species)
  File "/home/connie/Research/Code/RMG-Py/rmgpy/data/transport.py", line 337, in getTransportPropertiesViaGroupEstimates
    criticalPoint = self.estimateCriticalPropertiesViaGroupAdditivity(molecule)
  File "/home/connie/Research/Code/RMG-Py/rmgpy/data/transport.py", line 434, in estimateCriticalPropertiesViaGroupAdditivity
    self.__addCriticalPointContribution(groupData, self.groups['ring'], molecule, {'*':atom})
  File "/home/connie/Research/Code/RMG-Py/rmgpy/data/transport.py", line 478, in __addCriticalPointContribution
    raise KeyError('Node {!r} has no parent with data in the transport database.'.format(node0))
KeyError: 'Node <Entry index=0 label="C_centered_ring"> has no parent with data in the transport database.'
```

But this does not occur when we use the SMILES representation c1ccccc1

**Comment by connie** [comment]
Use of benzene bonds in adjlists in input file is working now.
