### ISSUE TITLE
Unable to determine atom type for C=C1[CH]C(=O)C[C](C)O1

### ISSUE THREAD

**Issue by elnash** [GreenGroup/RMG-Py#340]
I received an error when running RMG. Looks like RMG is confused by the aromaticity of the molecule `C=C1[CH]C(=O)C[C](C)O1`

```python
Traceback (most recent call last):
  File "/RMG-Py/rmg.py", line 147, in <module>
    rmg.execute(args)
  File "/RMG-Py/rmgpy/rmg/main.py", line 506, in execute
    self.reactionModel.enlarge(objectsToEnlarge)
  File "/code/RMG-Py/rmgpy/rmg/model.py", line 689, in enlarge
    newReactions.extend(self.react(database, newSpecies, coreSpecies))
  File "/code/RMG-Py/rmgpy/rmg/model.py", line 637, in react
    reactionList.extend(database.kinetics.generateReactionsFromFamilies([moleculeA, moleculeB], products=None, failsSpeciesConstraints=self.failsSpeciesConstraints))
  File "/code/RMG-Py/rmgpy/data/kinetics/__init__.py", line 422, in generateReactionsFromFamilies
    reactionList.extend(family.generateReactions(reactants, failsSpeciesConstraints=failsSpeciesConstraints))
  File "/code/RMG-Py/rmgpy/data/kinetics/family.py", line 1218, in generateReactions
    reactionList.extend(self.__generateReactions(reactants, forward=True, failsSpeciesConstraints=failsSpeciesConstraints))
  File "/code/RMG-Py/rmgpy/data/kinetics/family.py", line 1407, in __generateReactions
    products0 = [product.generateResonanceIsomers() for product in products0]
  File "rmgpy/molecule/molecule.py", line 1662, in rmgpy.molecule.molecule.Molecule.generateResonanceIsomers (build/pyrex/rmgpy/molecule/molecule.c:30323)
  File "rmgpy/molecule/molecule.py", line 1682, in rmgpy.molecule.molecule.Molecule.generateResonanceIsomers (build/pyrex/rmgpy/molecule/molecule.c:30167)
  File "rmgpy/molecule/molecule.py", line 900, in rmgpy.molecule.molecule.Molecule.updateAtomTypes (build/pyrex/rmgpy/molecule/molecule.c:17166)
  File "rmgpy/molecule/atomtype.py", line 324, in rmgpy.molecule.atomtype.getAtomType (build/pyrex/rmgpy/molecule/atomtype.c:5816)
  File "rmgpy/molecule/atomtype.py", line 405, in rmgpy.molecule.atomtype.getAtomType (build/pyrex/rmgpy/molecule/atomtype.c:5689)
rmgpy.molecule.atomtype.AtomTypeError: Unable to determine atom type for atom C, which has 0 double bonds to C, 1 double bonds to O, 0 triple bonds, and 2 benzene bonds.
```
This error can be recreated by searching reactions for the molecule `(C=C1[CH]C(=O)C[C](C)O1)` on http://rmg.mit.edu/database/kinetics/search/. (http://goo.gl/rSr5rU)

**Comment by elnash** [comment]
Fixed by https://github.com/GreenGroup/RMG-Py/commit/e96b3f66b357805cbf9b990e55d1720cce695523 ?

**Comment by elnash** [comment]
Crashed after recent change as well:

""Traceback (most recent call last):
  File "/home/nash.el/code/RMG-Py/rmg.py", line 139, in <module>
    cProfile.runctx(command, global_vars, local_vars, stats_file)
  File "/shared/apps/python/Python-2.7.5/INSTALL/lib/python2.7/cProfile.py", line 49, in runctx
    prof = prof.runctx(statement, globals, locals)
  File "/shared/apps/python/Python-2.7.5/INSTALL/lib/python2.7/cProfile.py", line 140, in runctx
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "/home/nash.el/code/RMG-Py/rmgpy/rmg/main.py", line 438, in execute
    self.initialize(args)
  File "/home/nash.el/code/RMG-Py/rmgpy/rmg/main.py", line 426, in initialize
    self.reactionModel.enlarge([spec for spec in self.initialSpecies if spec.reactive])
  File "/home/nash.el/code/RMG-Py/rmgpy/rmg/model.py", line 684, in enlarge
    newReactions.extend(self.react(database, newSpecies))
  File "/home/nash.el/code/RMG-Py/rmgpy/rmg/model.py", line 632, in react
    reactionList.extend(database.kinetics.generateReactionsFromFamilies([moleculeA], products=None, failsSpeciesConstraints=self.failsSpeciesConstraints))
  File "/home/nash.el/code/RMG-Py/rmgpy/data/kinetics/__init__.py", line 422, in generateReactionsFromFamilies
    reactionList.extend(family.generateReactions(reactants, failsSpeciesConstraints=failsSpeciesConstraints))
  File "/home/nash.el/code/RMG-Py/rmgpy/data/kinetics/family.py", line 1237, in generateReactions
    reactionList.extend(self.__generateReactions(reactants, forward=False, failsSpeciesConstraints=failsSpeciesConstraints))
  File "/home/nash.el/code/RMG-Py/rmgpy/data/kinetics/family.py", line 1407, in __generateReactions
    products0 = [product.generateResonanceIsomers() for product in products0]
  File "rmgpy/molecule/molecule.py", line 1662, in rmgpy.molecule.molecule.Molecule.generateResonanceIsomers (build/pyrex/rmgpy/molecule/molecule.c:30323)
  File "rmgpy/molecule/molecule.py", line 1682, in rmgpy.molecule.molecule.Molecule.generateResonanceIsomers (build/pyrex/rmgpy/molecule/molecule.c:30167)
  File "rmgpy/molecule/molecule.py", line 900, in rmgpy.molecule.molecule.Molecule.updateAtomTypes (build/pyrex/rmgpy/molecule/molecule.c:17166)
  File "rmgpy/molecule/atomtype.py", line 324, in rmgpy.molecule.atomtype.getAtomType (build/pyrex/rmgpy/molecule/atomtype.c:5816)
  File "rmgpy/molecule/atomtype.py", line 405, in rmgpy.molecule.atomtype.getAtomType (build/pyrex/rmgpy/molecule/atomtype.c:5689)
rmgpy.molecule.atomtype.AtomTypeError: Unable to determine atom type for atom C, which has 0 double bonds to C, 1 double bonds to O, 0 triple bonds, and 2 benzene bonds.""

**Comment by elnash** [comment]
'''python
Traceback (most recent call last):
  File "/home/nash.el/code/RMG-Py/rmg.py", line 139, in <module>
    cProfile.runctx(command, global_vars, local_vars, stats_file)
  File "/shared/apps/python/Python-2.7.5/INSTALL/lib/python2.7/cProfile.py", line 49, in runctx
    prof = prof.runctx(statement, globals, locals)
  File "/shared/apps/python/Python-2.7.5/INSTALL/lib/python2.7/cProfile.py", line 140, in runctx
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "/home/nash.el/code/RMG-Py/rmgpy/rmg/main.py", line 438, in execute
    self.initialize(args)
  File "/home/nash.el/code/RMG-Py/rmgpy/rmg/main.py", line 426, in initialize
    self.reactionModel.enlarge([spec for spec in self.initialSpecies if spec.reactive])
  File "/home/nash.el/code/RMG-Py/rmgpy/rmg/model.py", line 684, in enlarge
    newReactions.extend(self.react(database, newSpecies))
  File "/home/nash.el/code/RMG-Py/rmgpy/rmg/model.py", line 632, in react
    reactionList.extend(database.kinetics.generateReactionsFromFamilies([moleculeA], products=None, failsSpeciesConstraints=self.failsSpeciesConstraints))
  File "/home/nash.el/code/RMG-Py/rmgpy/data/kinetics/__init__.py", line 422, in generateReactionsFromFamilies
    reactionList.extend(family.generateReactions(reactants, failsSpeciesConstraints=failsSpeciesConstraints))
  File "/home/nash.el/code/RMG-Py/rmgpy/data/kinetics/family.py", line 1237, in generateReactions
    reactionList.extend(self.__generateReactions(reactants, forward=False, failsSpeciesConstraints=failsSpeciesConstraints))
  File "/home/nash.el/code/RMG-Py/rmgpy/data/kinetics/family.py", line 1407, in __generateReactions
    products0 = [product.generateResonanceIsomers() for product in products0]
  File "rmgpy/molecule/molecule.py", line 1662, in rmgpy.molecule.molecule.Molecule.generateResonanceIsomers (build/pyrex/rmgpy/molecule/molecule.c:30323)
  File "rmgpy/molecule/molecule.py", line 1682, in rmgpy.molecule.molecule.Molecule.generateResonanceIsomers (build/pyrex/rmgpy/molecule/molecule.c:30167)
  File "rmgpy/molecule/molecule.py", line 900, in rmgpy.molecule.molecule.Molecule.updateAtomTypes (build/pyrex/rmgpy/molecule/molecule.c:17166)
  File "rmgpy/molecule/atomtype.py", line 324, in rmgpy.molecule.atomtype.getAtomType (build/pyrex/rmgpy/molecule/atomtype.c:5816)
  File "rmgpy/molecule/atomtype.py", line 405, in rmgpy.molecule.atomtype.getAtomType (build/pyrex/rmgpy/molecule/atomtype.c:5689)
rmgpy.molecule.atomtype.AtomTypeError: Unable to determine atom type for atom C, which has 0 double bonds to C, 1 double bonds to O, 0 triple bonds, and 2 benzene bonds.    
'''

**Comment by elnash** [comment]
```python
Traceback (most recent call last):
File "/home/nash.el/code/RMG-Py/rmg.py", line 139, in 
cProfile.runctx(command, global_vars, local_vars, stats_file)
File "/shared/apps/python/Python-2.7.5/INSTALL/lib/python2.7/cProfile.py", line 49, in runctx
prof = prof.runctx(statement, globals, locals)
File "/shared/apps/python/Python-2.7.5/INSTALL/lib/python2.7/cProfile.py", line 140, in runctx
exec cmd in globals, locals
File "", line 1, in 
File "/home/nash.el/code/RMG-Py/rmgpy/rmg/main.py", line 438, in execute
self.initialize(args)
File "/home/nash.el/code/RMG-Py/rmgpy/rmg/main.py", line 426, in initialize
self.reactionModel.enlarge([spec for spec in self.initialSpecies if spec.reactive])
File "/home/nash.el/code/RMG-Py/rmgpy/rmg/model.py", line 684, in enlarge
newReactions.extend(self.react(database, newSpecies))
File "/home/nash.el/code/RMG-Py/rmgpy/rmg/model.py", line 632, in react
reactionList.extend(database.kinetics.generateReactionsFromFamilies([moleculeA], products=None, failsSpeciesConstraints=self.failsSpeciesConstraints))
File "/home/nash.el/code/RMG-Py/rmgpy/data/kinetics/init.py", line 422, in generateReactionsFromFamilies
reactionList.extend(family.generateReactions(reactants, failsSpeciesConstraints=failsSpeciesConstraints))
File "/home/nash.el/code/RMG-Py/rmgpy/data/kinetics/family.py", line 1237, in generateReactions
reactionList.extend(self.__generateReactions(reactants, forward=False, failsSpeciesConstraints=failsSpeciesConstraints))
File "/home/nash.el/code/RMG-Py/rmgpy/data/kinetics/family.py", line 1407, in __generateReactions
products0 = [product.generateResonanceIsomers() for product in products0]
File "rmgpy/molecule/molecule.py", line 1662, in rmgpy.molecule.molecule.Molecule.generateResonanceIsomers (build/pyrex/rmgpy/molecule/molecule.c:30323)
File "rmgpy/molecule/molecule.py", line 1682, in rmgpy.molecule.molecule.Molecule.generateResonanceIsomers (build/pyrex/rmgpy/molecule/molecule.c:30167)
File "rmgpy/molecule/molecule.py", line 900, in rmgpy.molecule.molecule.Molecule.updateAtomTypes (build/pyrex/rmgpy/molecule/molecule.c:17166)
File "rmgpy/molecule/atomtype.py", line 324, in rmgpy.molecule.atomtype.getAtomType (build/pyrex/rmgpy/molecule/atomtype.c:5816)
File "rmgpy/molecule/atomtype.py", line 405, in rmgpy.molecule.atomtype.getAtomType (build/pyrex/rmgpy/molecule/atomtype.c:5689)
rmgpy.molecule.atomtype.AtomTypeError: Unable to determine atom type for atom C, which has 0 double bonds to C, 1 double bonds to O, 0 triple bonds, and 2 benzene bonds.
```

**Comment by elnash** [comment]
It was indeed fixed by https://github.com/GreenGroup/RMG-Py/commit/e96b3f66b357805cbf9b990e55d1720cce695523 but I had forgotten to rebuild everything. After a `make` the error went away.
